#!/bin/bash

set -e

# CKAN user and database
psql --username=$POSTGRES_USER --command="CREATE USER $CKAN_POSTGRES_USER WITH PASSWORD '$CKAN_POSTGRES_USER_PWD' NOSUPERUSER NOCREATEDB NOCREATEROLE;"
createdb --encoding=utf-8  --username=$POSTGRES_USER --owner=$CKAN_POSTGRES_USER $CKAN_POSTGRES_DB

# DataStore users and database
psql --username=$POSTGRES_USER --command="CREATE USER $CKAN_DATASTORE_POSTGRES_READ_USER WITH PASSWORD '$CKAN_DATASTORE_POSTGRES_READ_PWD' NOSUPERUSER NOCREATEDB NOCREATEROLE;"
psql --username=$POSTGRES_USER --command="CREATE USER $CKAN_DATASTORE_POSTGRES_WRITE_USER WITH PASSWORD '$CKAN_DATASTORE_POSTGRES_WRITE_PWD' NOSUPERUSER NOCREATEDB NOCREATEROLE;"
createdb --encoding=utf-8  --username=$POSTGRES_USER --owner=$CKAN_DATASTORE_POSTGRES_WRITE_USER $CKAN_DATASTORE_POSTGRES_DB
